Fix PowerMock related tests due to version bump (#637)
2.2 added a new dependency of ClusterSettings like TaskResourceTrackingService. It is possible that the classloader that loadsTaskResourceTrackingService is different from the classloader that loads PowerMock and related dependencies. PowerMock reports java.lang.NoClassDefFoundError when initializing ClusterSettings. Since we are not actually using the value of ClusterSettings in the tests, we make it null to avoid initializing it. The change fixed failed tests.

This PR also fixed spotless errors in FakeNode due to recent changes.

Testing done:
* gradle build

Signed-off-by: Kaituo Li <kaituo@amazon.com>
(cherry picked from commit c92cdc82fb2aef58b3c0b95fafa90da81bfc24cf)